### ISSUE TITLE
Cannot install the Count macro

### ISSUE THREAD

**Issue by educlos** [aws-cloudformation/aws-cloudformation-macros#10]
I've cloned the repo and followed the the steps on README (aka I created an s3 bucket then ran the `deploy.sh` script.
However I have the following error on the deploy step:
```
Received malformed response from transform AWS::Serverless-2016-10-31
```
Am I missing something?

**Comment by ericzbeard** [comment]
We are archiving this repository in favor of similar content located here: https://github.com/aws-cloudformation/aws-cloudformation-templates/tree/main/aws/services/CloudFormation/MacrosExamples
