### ISSUE TITLE
Parameterize CloudFormation Count Macro

### ISSUE THREAD

**Issue by bhabanisankar** [aws-cloudformation/aws-cloudformation-macros#14]
Hi Team,
We are trying to parameterize the Count value(eg. 2, 3 or any value) by passing the parameter from JSON file to the Cloud formation template. But we are getting error as "**Received malformed response from transform**". Could you please help us to fix this? if it is possible to parameterize the Count Macro, please share the  the steps needs to carried out to fix this issue.

**Comment by nitinarora1989** [comment]
@bhabanisankar - have you got any solution for this issue?

**Comment by bhabanisankar** [comment]
Hi @nitinarora1989- yeah, I have got the solution and that has implemented
and tested successfully.

Thanks!!
Bhabani Dixit

**Comment by MichaelKing54** [comment]
What is the solution for this?

**Comment by hybridadmin** [comment]
> Hi @nitinarora1989- yeah, I have got the solution and that has implemented and tested successfully. Thanks!! Bhabani Dixit
> […](#)

would you be willing to share the solutions that you came up with, would be greatly appreciated as I have been looking for a solution for this as well  ?
