### ISSUE TITLE
Update python version for boto3 macro

### ISSUE THREAD

**Issue by zaro0508** [aws-cloudformation/aws-cloudformation-macros#16]
The boto3 macro is [setup with python2.7](https://github.com/aws-cloudformation/aws-cloudformation-macros/blob/master/Boto3/macro.template#L7) which is EOL and not even supported by SAM any longer which means it will fail to deploy to AWS.  Would be great if this macro can be updated with a newer supported version of python.  

```
AWS CloudFormation Linter................................................Failed

- hook id: cfn-python-lint

- exit code: 2

E2531 Deprecated runtime (python2.7) specified. Updating disabled since 2021-09-30. Please consider updating to python3.8

template.yaml:5:3
```

**Comment by ericzbeard** [comment]
We are archiving this repository in favor of similar content located here: https://github.com/aws-cloudformation/aws-cloudformation-templates/tree/main/aws/services/CloudFormation/MacrosExamples
