### ISSUE TITLE
Duplicate repository 

### ISSUE THREAD

**Issue by rostskadat** [aws-cloudformation/aws-cloudformation-macros#5]
Hello,

I open a pull request [awslabs/aws-cloudformation-templates/pull/273](https://github.com/awslabs/aws-cloudformation-templates/pull/273) because I though that was the "official" repository for Macro Example. However I stumbled upon this repository.

Could you advise as to which repository should be used in order to get a new Cloudformation Macro example included?

Thanks a lot

**Comment by ericzbeard** [comment]
We are archiving this repository in favor of similar content located here: https://github.com/aws-cloudformation/aws-cloudformation-templates/tree/main/aws/services/CloudFormation/MacrosExamples
